### ISSUE TITLE
linear_regress_model.pth missing

### ISSUE THREAD

**Issue by WongChen** [MingXiangL/DEVIL#1]
Thx for your excellent work. When do you plan to upload the learned linear_regress model weights 🤔

**Comment by MingXiangL** [comment]
Thank you for your nice words！We are currently rearranging our code. The complete repo is coming soon！



---Original---
From: "Wong ***@***.***&gt;
Date: Wed, Aug 28, 2024 16:17 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [MingXiangL/DEVIL] linear_regress_model.pth missing (Issue #1)




 
Thx for your excellent work. When do you plan to upload the learned linear_regress model weights 🤔

**Comment by MingXiangL** [comment]
Hello, model weight is released.
