### ISSUE TITLE
是否可以出一个详细的readme

### ISSUE THREAD

**Issue by schhaohao** [MingXiangL/DEVIL#2]

**Comment by MingXiangL** [comment]
您好，感谢您对我们工作的关注，我们近期正在整理代码，很快会给出验证的仓库！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月4日(周三) 晚上8:23
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [MingXiangL/DEVIL] 是否可以出一个详细的readme (Issue #2)

**Comment by MingXiangL** [comment]
您好，readme已更新，有新的问题欢迎随时提issue～
