### ISSUE TITLE
您好，请问模型是没有放出来吗

### ISSUE THREAD

**Issue by schhaohao** [MingXiangL/DEVIL#5]
![image](https://github.com/user-attachments/assets/6be2d595-7376-4dd6-ace7-633f5d579ca5)
这个模型是没有fang放出来吗

**Comment by MingXiangL** [comment]
您好，模型权重已经更新，其余的prompt、完整的代码在国庆后也将放出！

**Comment by Ji4chenLi** [comment]
请问可以顺便放一下prompt吗，想赶紧拿来测一测哈哈

**Comment by MingXiangL** [comment]
目前正在整理哈，由于前段时间太多紧急的项目了，耽误了一些时间，我争取今天把prompt整理好哈

**Comment by Ji4chenLi** [comment]
多谢！辛苦了

**Comment by MingXiangL** [comment]
您好，仓库现已更新，另外，我们最近还将发布一版新的prompt，并评测最新的模型，敬请期待😊
